import '../css/app.css'
import '../css/style.css'
import './core/bootstrap.min.js'
import './core/popper.min.js'
import './plugins/tilt.min.js'
import './plugins/highlight.min.js'
import './plugins/choices.min.js'
import './plugins/countup.min.js'
import './plugins/flatpickr.min.js'
import './plugins/rellax.min.js'
import './plugins/parallax.min.js'
import {Vue} from 'vue'
//import './material-kit.js'
//import './carousel.js'

